### ISSUE TITLE
"undefined" bug when persisting data

### ISSUE THREAD

**Issue by sidharthv96** [MacFJA/svelte-persistent-store#11]
Been using this awesome project heavily in our app! 
Saw a bug that was kindof tricky to catch.

```ts
import { writable } from "svelte/store";
import type { Writable } from "svelte/store";
import { localStorage, persist } from "@macfja/svelte-persistent-store";

export interface User {
  name: string;
}
export const userStore: Writable<User> = persist(
  writable(),
  localStorage(),
  "userStore"
);
```

```svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { userStore } from "./store";

  onMount(() => {
    console.log("store", $userStore);
    console.log(typeof $userStore);
  });
</script>
```

When we refresh after initial load, the value goes from `undefined` to `"undefined"`

<img width="279" alt="image" src="https://user-images.githubusercontent.com/10703445/139378793-10467870-d382-4714-adbf-ce88c83c3bf2.png">

This in turn breaks all the object access in the code like `if(data?.x.y == "y")` 

The issue is that the check is only for `null`, not `undefined`.
https://github.com/MacFJA/svelte-persistent-store/blob/502efa9515513d483d721f3263172051b13e1b36/src/index.ts#L63-L68

I don't think we can simply add `  if (null !== initialValue || undefined !== initialValue) ` as the null check seems to be used in many places in the code.

**Comment by MacFJA** [comment]
In fact the issue exist for `sessionStorage`, `localStorage` and `cookie`.

Values are encoded with `JSON.stringify` as they only handle string,  
but `JSON.stringify` it don't have any _"transformation"_ for `undefined`,  
so ultimately when value is saved into the storage, an implicit cast to string is done, and the value is converted to the string `'undefined'`
