### ISSUE TITLE
[question] Is it possible to encrypt localStorage?

### ISSUE THREAD

**Issue by beebase** [MacFJA/svelte-persistent-store#21]
thanks.

**Comment by MacFJA** [comment]
Right now, no.
The built in Storage don't provide this feature.

But I was able to easily create a new Storage that encrypt data.

I will publish it when I finish to rewrite the serialization part (not that far), except if you urgently need the encryption storage

**Comment by beebase** [comment]
That's ok, It's not urgent. I'm using encryptjs right now before storing/reading.
I just thought it would be convenient skipping that extra code step if svelte-persistent-store could handle that internally.

I'm really enjoying using svelte-persistent-store.  Works well with all the browser storage options and it's cool to have this in one package with very easy syntax.
Thanks so much and I'll just patiently wait for a next release. 👍

**Comment by MacFJA** [comment]
Here the new encryption storage: https://github.com/MacFJA/svelte-persistent-store/blob/update/.docs/Examples/04-Encrypted-Storage.md

It will be added in a few day when the PR #22 is merged

The version will probably bump to `2.0.0` as there are many changes that break backward compatibility
