### ISSUE TITLE
How to prevent initialization from overwriting a previously persisted value

### ISSUE THREAD

**Issue by nltesown** [MacFJA/svelte-persistent-store#28]
I'm having trouble figuring this out: suppose I define a persistent store like this:

```js
const currentId = persist(writable(null), localStorage(), "currentId");
```

There is necessarily an initial value (here `null`), which is written to the store (and localStorage). But if the user has already set some value from a previous session, that value will be overwritten to `null`, which is probably not the desired behaviour.

Any idea how to deal with that?

**Comment by MacFJA** [comment]
Hello,

I can't reproduce the error.
I try it with version `2.0` and `1.3`
Here the test application I use

```svelte
<script>
    import { persist, localStorage } from "@macfja/svelte-persistent-store"
    import { writable } from "svelte/store"

    let nullExample = persist(writable(null), sessionStorage(), 'sps-null')
</script>

<fieldset>
    <legend>Null in storage</legend>
    <code>{$nullExample}</code> &rarr; <var>{typeof $nullExample}</var>
    <input bind:value={$nullExample} />
</fieldset>

<button id="reloadButton" on:click={() => window.location.reload()}>Reload the page</button>
```

**Comment by nltesown** [comment]
Thanks for your answer, and it looks like you're right: it works. Sorry about the false alert.
