### ISSUE TITLE
Build failed when compiling with adapter-cloudflare

### ISSUE THREAD

**Issue by kroniapp** [MacFJA/svelte-persistent-store#31]
Starting from version 2.0.0, in Sveltekit I cannot compile with adapter-cloudflare.

The error I am receiving is:

```
Error: Build failed with 2 errors:
.svelte-kit/output/server/chunks/lists.js:2:14: ERROR: Could not resolve "util"
.svelte-kit/output/server/chunks/lists.js:3:14: ERROR: Could not resolve "crypto"
```

I'm using Sveltekit with SSR disabled, so no Node packages are allowed.

From what I found reading the source code, I think the problem is with the new "cyrup" dependency added from version 2.0.0, which imports the two Node packages.

**Comment by MacFJA** [comment]
Hello,

Can you try with the version `2.1.0` ?
This version should fix the issue `require "util"` and `require "crypto"`

**Comment by kroniapp** [comment]
Yes, I also tried version `2.1.0`, but it give me the same error.

I created a project to reproduce the error https://stackblitz.com/edit/sveltejs-kit-template-default-tqmyfx?file=src/routes/+page.svelte

I also want to thank you for this library, good job!

**Comment by kroniapp** [comment]
Do you have the time to look at this issue? It's blocking my deployments

**Comment by MacFJA** [comment]
I try many configurations, tricks, but I can't achieve to have the compilation work.

I have an ugly workaround (which is editing the library dist file before building) but it's not a very practical or usable solution in an automated pipeline.

---

Others solutions that I have are:
- Make the crypto lib dependency optional, but require extra work to check is the dependency is installed or not (+ BC break).
- Make the encrypted storage a separate package, but that add more steps and workflow for publishing (+ BC break).
- Change the crypto lib dependency to `crypto-es`, but we loose native function as it's a pure JS implementation, so probably less performant.

_(I will probably go with the last one, as it introduce the fewer changes for users)_

**Comment by danawoodman** [comment]
I bet it is the dep `cyrup`

**Comment by MacFJA** [comment]
@kroniapp I just publish the version `2.2.0` that fix the error.
It took way longer than I have expected, sorry about that
