### ISSUE TITLE
Adding a class with addSerializableClass() shows an error

### ISSUE THREAD

**Issue by wojexe** [MacFJA/svelte-persistent-store#32]
I have encountered the attached error message when I tried adding my class to be serializable with `addSerializableClass()`.

This example [03-Store-Classes.md](https://github.com/MacFJA/svelte-persistent-store/blob/main/.docs/How-To/03-Store-Classes.md) seems to show the error message as well.

```
Argument of type 'typeof NameHolder' is not assignable to parameter of type'FunctionConstructor'.
  Types of property 'prototype' are incompatible.
    Type 'NameHolder' is missing the following properties from type 'Function': apply, call, bind, prototype, and 4 more. js(2345)
```

edit:
I understand, this might not be a problem of package itself, but I think that it's worth mentioning, that such error might occur. As for now, I was able to just ignore the error and everything seems to work as expected.
I have also created a quick [CodeSandbox](https://codesandbox.io/s/svelte-persistent-store-bug-ddg926) with the example and there is no such error in there.

**Comment by MacFJA** [comment]
It's indeed not a true error as the code won't stop working.
But the typing is not correct, I have to find the correct one.

Maybe something like :thinking: 
```ts
type ClassDefinition<T> = new (...args:any[]) => T;
export const addSerializableClass = (classDef: FunctionConstructor|ClassDefinition<any>): void => {
  addSerializable(classDef)
}
```

**Comment by wojexe** [comment]
This type works for me.

The only thing is - it doesn't work with private class constructors - and it was probably not intended to work with those. It might be worth mentioning that in the docs, if it's not already there :)

FYI, the error that's showing up when the constructor is private, is nearly identical to the one shown before. This line is preceding the rest: `Argument of type 'typeof NameHolder' is not assignable to parameter of type 'FunctionConstructor | ClassDefinition<any>'.`

**Comment by MacFJA** [comment]
> The only thing is - it doesn't work with private class constructors - and it was probably not intended to work with those. It might be worth mentioning that in the docs, if it's not already there :)

It's possible, but it needs a bit more configuration:
- First install `@macfja/serializer` as a project dependency
- next in your code (in the earliest position, ie. the booting of the App):
```ts
import { addClassHandler, serialize, deserialize, addGlobalAllowedClass } from "@macfja/serializer"
import { setSerializer } from "@macfja/svelte-persistent-store"

addClassHandler(
  "MyClass",
  (source: MyClass, next) => {
    return { prop1: source.prop1, property2: next(source.prop2) }
  },
  (source, next) => {
    return MyClass.createInstance(source.prop1, next(source.property2))
  }
)
setSerializer(serialize, deserialize, addGlobalAllowedClass)
```

**Comment by MacFJA** [comment]
@wojexe I just publish the version `2.2.1` that resolve the issue.
(The `@macfja/serializer` lib have also been updated)
