### ISSUE TITLE
Fallback if `localStorage` is not available.

### ISSUE THREAD

**Issue by gyurielf** [MacFJA/svelte-persistent-store#41]
Hello there!

I met a quite edge case issue while using the package.

In chrome, if you have an embed `iframe` on a site (which uses this package), and you open it in `incognito mode` it will be throws an error.
`Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`
I walked around the issue, so it's a chrome specific issue which is exists on both mobile and desktop (tested on win, ubuntu, android), 
 
I tried to handle on the the lacking of `localStorage` in a `+page.ts` `load` and throwing the user to a meaningful error page, but files are loaded by the browser when the document load starts and it's try to "connect" to the `localStorage` instantly and unfortunately it's kill the app before it can be handled by a svelte-kit `load` function.

I thought about a fallback option or something like that. I mean if it can't read the `localStorage`, drop a meaningful error but make a regular store regardless to prevent app breaks.

The title probably not too precise, so modify freely.

Best regards.

**Comment by gyurielf** [comment]
I look into the code and as I see you did something like that.
https://github.com/MacFJA/svelte-persistent-store/blob/584b57b8f63d68f564063a9754c659fa9f24715d/src/core.ts#L286-L292

Maybe it's a svelte-kit issue then ?

**Comment by MacFJA** [comment]
I never encountered this case before.
I will try to handle it like when the `localStorage` doesn't exist

----

> Maybe it's a svelte-kit issue then ?

It's not an issue with SvelteKit, the issue came from the `iframe` being sandboxed by default.
You can use `localStorage` in an `iframe`, but you have to allow it before (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#sandbox)

**Comment by gyurielf** [comment]
Well, shame on me, but i forgot to mention that this issue occurs only on incognito mode.

**Comment by MacFJA** [comment]
I just push the version `2.3.0` that should fix this kind of errors

**Comment by gyurielf** [comment]
I've tested it, working like a charm. Thank you for the super fast reply and fix!
