### ISSUE TITLE
Persist with array of objects turns into escaped string unexpectedly

### ISSUE THREAD

**Issue by PlusA2M** [MacFJA/svelte-persistent-store#44]
### What's happening?
Hi @MacFJA ! Thanks for your amazing works, I've been using the library for months now, found that it may have issue with array of objects. Interestingly, if I turn the array of objects to array of a object `[weirdObject]`, the error disappear. The array of objects `[obj1, obj2, obj3, ...]` turns into string with backslash once after refresh, hence the issue may related to the deserialize process also.

### What do I know
After examine a bit from the console, the object does set as correct array of objects at the first time (Chrome console display it correctly), but then the array of objects become string with lots of backslash after refresh.

edit:
I found that it's due to two element in the object,
1) merchant object 
2) another promise element in the object

**Does the merchant object overload with the serialization process due to the `locationRemarks` making it become 3-d object?**

### The code
`weirdObject: Writable<Awaited<ReturnType<typeof functionThatReturnObject>>> = persistBrowserLocal(writable([]), 'weirdObject')`

In `+layout.svelte`
`$weirdObject = functionThatReturnObject()`

### Example of the object
```
{
   ...other fields
    "merchant": {
        "id": "uuid-2",
        "name": "hedonic",
        "email": null,
        "address": "address",
        "phone": "+112214324",
        "altPhone": null,
        "dutyPhone": null,
        "area": "XYZ",
        "region": "hi",
        "officeHour": null,
        "availableProducts": null,
        "locationRemarks": {
            "side": "left",
            "pickup_at_road": false
        },
        "pricing": null,
        "remarks": null,
        "slug": "hedonic",
        "prefix": "PRE",
        "paymentTerm": null,
        "ownerSub": null,
        "employees": null,
        "createdAt": "2023-02-18T04:54:43.286Z",
        "updatedAt": "2023-02-18T05:06:17.132Z",
        "_version": 2,
        "_lastChangedAt": 1676696777181,
        "_deleted": null
    },
    "PromiseObject": "Promise<Array>"
}
```

### The string in localStorage after refresh 
(in this example we have two objects in the array. `[obj1, obj2]`
```
"[\"#$@__reference__0\",{\"id\":\"uuid\",\"ref\":\"HED-002-3144\",\"startsRescheduledFrom\":null,\"endsAt\":null,\"date\":\"2023-05-09\",\"timeslot\":\"19:00~19:30\",\"startsAt\":1683630000,\"to\":\"TO\",\"toRegion\":\"AA\",\"fromRegion\":\"BB\",\"from\":\"hedonic\",\"up\":false,\"phone\":\"+PHONE\",\"status\":\"STATUS\",\"comment\":\"COMMENT\",\"receipt\":null,\"photos\":null,\"merchant\":{\"#$@__constructor__\":\"Merchant\",\"#$@__reference__\":2,\"id\":\"uuid-2\",\"name\":\"hedonic\",\"email\":null,\"address\":\"address\",\"phone\":\"+PHONE\",\"altPhone\":null,\"dutyPhone\":null,\"area\":\"AREA\",\"region\":\"mo\",\"officeHour\":null,\"availableProducts\":null,\"locationRemarks\":{\"side\":\"left\",\"pickup_at_road\":false,\"#$@__reference__\":3},\"pricing\":null,\"remarks\":null,\"slug\":\"hedonic\",\"prefix\":\"PRE\",\"paymentTerm\":null,\"ownerSub\":null,\"employees\":null,\"createdAt\":\"2023-02-18T04:54:43.286Z\",\"updatedAt\":\"2023-02-18T05:06:17.132Z\",\"_version\":2,\"_lastChangedAt\":1676696777181,\"_deleted\":null},\"rescheduledAt\":null,\"cancelledAt\":null,\"fromBackend\":false,\"type\":\"type1\",\"#$@__reference__\":1},{\"id\":\"uuid-3\",\"ref\":\"REF\",\"startsRescheduledFrom\":null,\"endsAt\":null,\"date\":\"2023-05-07\",\"timeslot\":\"19:30~20:00\",\"startsAt\":1683459000,\"to\":\"15/D\",\"toRegion\":\"BB\",\"fromRegion\":\"CC\",\"from\":\"DDD\",\"up\":false,\"phone\":\"+113423234\",\"status\":\"status\",\"comment\":\"\",\"receipt\":null,\"photos\":null,\"merchant\":{\"prefix\":\"NOT\",\"name\":\"\",\"#$@__reference__\":5},\"rescheduledAt\":null,\"cancelledAt\":null,\"fromBackend\":false,\"type\":\"other\",\"#$@__reference__\":4}]"
```

**Comment by PlusA2M** [comment]
The issue is due to some non-serializable object like promise object or constructor in the object, the issue is resolved after redesign the object structure.

**Comment by MacFJA** [comment]
The library use [@macfja/serializer](https://www.npmjs.com/package/@macfja/serializer) as it's default serializer ([other serializer are possible](https://github.com/MacFJA/svelte-persistent-store/blob/main/.docs/How-To/06-Change-Serialization.md)) which is capable of serializing classes, but you have to declare them.

As for Promise, you either have to rerun them on deserialization (you have to be able to serialize how to recreate them) or you have to wait the resolution of the promise before saving them (a custom store that update only when promise are resolved can be used to to that)
