### ISSUE TITLE
how to use in sveltekit

### ISSUE THREAD

**Issue by shellking4** [MacFJA/svelte-persistent-store#45]
How to use it in sveltekit, I want to understand how I can check for browser in order to get the stores data to avoid errors like browser is not defined

**Comment by MacFJA** [comment]
If the library can't use a storage, the Svelte store will be used as normal.
It will add a warning in the console ([which can be disabled](https://github.com/MacFJA/svelte-persistent-store/blob/main/.docs/How-To/04-Disable-Warnings.md)).

The way to tell if you are in browser rendering or server rendering (in a SvelteKit application) is the same as usual: using [`browser` from `$app/environment`](https://kit.svelte.dev/docs/modules#$app-environment-browser)
