### ISSUE TITLE
 WARN  Issues with peer dependencies found (Svelte 4)

### ISSUE THREAD

**Issue by elron** [MacFJA/svelte-persistent-store#48]
After updating my svelte app to svelte 4, I get this error:
```
 WARN  Issues with peer dependencies found
.
└─┬ @macfja/svelte-persistent-store 2.3.0
  └── ✕ unmet peer svelte@^3.0: found 4.0
```

To fix the issue, I see you updated `package.json` to this:

```
    "peerDependencies": {
        "svelte": "^3.0 || ^4.0"
    },
```

and it will work,
but the NPM package need to be updated.
Can you please publish the next release?

`npm publish`

Thanks

**Comment by MacFJA** [comment]
I will publish a new release tomorrow with the compatibility with Svelte 4

**Comment by elron** [comment]
Thanks
If you need steps easy, these are pretty straightforward (I used these steps in my svelte libraries and it got rid of the error):

1. run `npm svelte-migrate@latest svelte-4` [source](https://svelte.dev/blog/svelte-4)
2. run `npm update` (to update package.json file)
3. in package.json update the version number
4. run `npm publish`

I appreciate your maintenance of the project!

**Comment by MacFJA** [comment]
I just publish the version `2.3.1` which add the compatibility with Svelte 4.

It was a bit more complicated as some dependencies were a bit hard to update.

**Comment by elron** [comment]
Works! Thanks a lot
