### ISSUE TITLE
How to fix index.mjs' implicitly has an 'any' type?

### ISSUE THREAD

**Issue by biplobsd** [MacFJA/svelte-persistent-store#50]
After npm install `npm install -D  @macfja/svelte-persistent-store` I get this error.
I also restart VSCode but error still rise.

## Error text:
```
Could not find a declaration file for module '@macfja/svelte-persistent-store'. 'g:/project/as/node_modules/@macfja/svelte-persistent-store/dist/index.mjs' implicitly has an 'any' type.
  There are types at 'g:/project/as/node_modules/@macfja/svelte-persistent-store/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@macfja/svelte-persistent-store' library may need to update its package.json or typings.ts(7016)
```

## Here is a screenshot below 
![image](https://github.com/MacFJA/svelte-persistent-store/assets/43641536/36ec15ca-3492-435c-a96b-76e6371e8ca2)

**Comment by MacFJA** [comment]
That's very strange:
- `package.json` declare a `types` node
- the `types` node is pointing to `types/index.d.ts`
- the file `types/index.d.ts` exist
- the file `types/index.d.ts` export `writable` from `./alias`
- the file `types/alias.d.ts` exist
- the file `types/alias.d.ts` export the definition of `writable`

I should have miss something

**Comment by MacFJA** [comment]
After some quick test, it seems that declaring the `types` in the `exports` works.

Look like we can't have both `exports` and `types` at the root of the `package.json`
[The documentation indicate](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing) that be default Typescript search for a declaration in the same directory of the imported file, but it don't indicate that `types` (at root level of `package.json`) is not used as a fallback

----

I will update teh lib to add `types` inside the `exports` node

**Comment by biplobsd** [comment]
I'll waiting for this.
Currently I just ignored types.. And it is working well...

**Comment by MacFJA** [comment]
I just publish the version `2.3.2` that should solve the typing issue
