### ISSUE TITLE
[Suggestion] Cookie Options such as expiry for Cookie Stores

### ISSUE THREAD

**Issue by Lowisz** [MacFJA/svelte-persistent-store#52]
It would be great if there were a way to set/change some cookie options on cookie stores, such as ``expiry``.

Use Case: An API issues a JWT token that expires after x time, and after expiring, the svelte app doesn't know that the token has expired while it continues trying to use that token. This behavior leads to errors when fetching data using the now expired token.

If it were possible to set expiry dates to cookies, then it would've been possible to know that the token isn't valid anymore because the cookie would return ``undefined``.

While this could easily be done by creating the cookies manually, it would be great to have the option to do it using this package.

Thanks.

**Comment by MacFJA** [comment]
I released the version 2.4.0 which integrate an additional parameter in the `createCookieStorage` to add cookie options

**Comment by Catsvilles** [comment]
What about an expiration option for createIndexedDBStorage?
