### ISSUE TITLE
Svelte 5 Support

### ISSUE THREAD

**Issue by Mtn-View** [MacFJA/svelte-persistent-store#59]
Would it be possible to support Svelte 5? The stores API is unchanged, so in theory it should just be a matter of allowing Svelte 5 as a peer dependency

**Comment by MacFJA** [comment]
I just released the version `2.4.2` that allow Svelte 5 :slightly_smiling_face:

**Comment by ahmedra13579** [comment]
maybe this solution will solve your problem [link](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Mtn-View** [comment]
Thank you!
